version: '3'
services:
  api:
    build: ./
    restart: always
    depends_on:
      - "redis"
    env_file:
      - .variables.env
    ports:
      - "8080:80"
    networks:
      default:

  redis:
    image: redis
    command: redis-server --appendonly yes --replica-read-only no
    networks:
      default:
